# -*- coding: utf-8 -*-
"""web scraping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLCo6brj1pU3LzmDRNjRkLQmKnK1IPgW
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

web = requests.get('https://quotes.toscrape.com/')
web

soup = BeautifulSoup(web.content, 'html.parser')
print(soup.prettify())

author = []
authors = soup.find_all('small',class_='author')
for a in authors:
    author.append(a.text)
print(author)

quote = []
quotes = soup.find_all('span',class_='text')
for q in quotes:
    quote.append(q.text)
print(quote)

df = pd.DataFrame({'Author':author,'Quote':quote})
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)  # increase console width
pd.set_option('display.max_colwidth', None)
df

df.to_csv('quotes.csv', index=False)
df

